---
REPORT_OUTPUT_FOLDER: none
PARALLEL_PROCESS_NUMBER: 11
OUTPUT_FORMAT: text
EXCLUDED_DIRECTORIES:
  - ".git"
  - ".vscode"
BASH_SHFMT_ARGUMENTS: "-i 2"
REPOSITORY_CHECKOV_ARGUMENTS: "--skip-check CKV2_GHA_1"
PRINT_ALL_FILES: true
EDITORCONFIG_EDITORCONFIG_CHECKER_CLI_EXECUTABLE:
  - /ec-custom.sh
EDITORCONFIG_EDITORCONFIG_CHECKER_PRE_COMMANDS:
  - command: |
      cat <<EOF > /ec-custom.sh
      #!/usr/bin/env bash
      editorconfig-checker \$@
      rc=\$?
      # check for multiple empty lines at EOF
      for file in \$@; do
        tail_lines=\$(tail -n 2 "\$file" | grep -c '^$')
        if [ "\$tail_lines" -gt 1 ]; then
          echo "File [\$file] has multiple trailing line"
          rc=\$((rc + 1))
        fi
      done
      exit \$rc
      EOF
      chmod -v 755 /ec-custom.sh
    cwd: workspace
    continue_if_failed: True
