# kics-scan disable=555ab8f9-2001-455e-a077-f2d0f41e2fb9
---
name: build PDFs
on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "11 11 * * 1"
jobs:
  build-n-push:
    name: build PDFs
    timeout-minutes: 22
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - name: build PDFs
        if: >-
          github.event_name == 'pull_request' || (
            (github.event_name == 'schedule' || github.event_name == 'push')
          ) && github.ref == 'refs/heads/master'
        run: bin/build.sh
      - name: make draft and upload PDFs
        if: >-
          (github.event_name == 'schedule' || github.event_name == 'push')
          && github.ref == 'refs/heads/master'
        uses: ncipollo/release-action@v1
        with:
          name: >
            branch [${{
              github.head_ref == '' && github.ref_name || github.head_ref
            }}] resume
          draft: true
          allowUpdates: true
          tag: v999
          artifacts: "*.pdf"
          body: >
            branch [${{
              github.head_ref == '' && github.ref_name || github.head_ref
            }}] resume from recent commit by GitHub actions
  linters:
    name: check linters
    timeout-minutes: 11
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - name: MegaLinter
        uses: oxsecurity/megalinter@v8
        env:
          VALIDATE_ALL_CODEBASE: true
