---
name: build PDFs
on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "11 11 * * 1"
jobs:
  build-n-push:
    name: build PDFs
    timeout-minutes: 22
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - name: build PDFs
        run: bin/build.sh
